// Enum definitions (these will be generated by Prisma)
const FindingType = {
  VULNERABILITY: 'VULNERABILITY',
  SUSPICIOUS_PATTERN: 'SUSPICIOUS_PATTERN',
  COMPLIANCE_ISSUE: 'COMPLIANCE_ISSUE',
  CODE_SMELL: 'CODE_SMELL',
  SECURITY_BEST_PRACTICE: 'SECURITY_BEST_PRACTICE',
  FINANCIAL_RISK: 'FINANCIAL_RISK',
  LIQUIDITY_RISK: 'LIQUIDITY_RISK',
  GOVERNANCE_RISK: 'GOVERNANCE_RISK',
} as const;

const Severity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

const RiskLevel = {
  MINIMAL: 'MINIMAL',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

const Network = {
  ETHEREUM: 'ETHEREUM',
  POLYGON: 'POLYGON',
  BSC: 'BSC',
  ARBITRUM: 'ARBITRUM',
  OPTIMISM: 'OPTIMISM',
  AVALANCHE: 'AVALANCHE',
  FANTOM: 'FANTOM',
  BASE: 'BASE',
} as const;

const ContractType = {
  ERC20: 'ERC20',
  ERC721: 'ERC721',
  ERC1155: 'ERC1155',
  GOVERNANCE: 'GOVERNANCE',
  STAKING: 'STAKING',
  DEFI_PROTOCOL: 'DEFI_PROTOCOL',
  BRIDGE: 'BRIDGE',
  MULTISIG: 'MULTISIG',
  CUSTOM: 'CUSTOM',
} as const;

const IncidentStatus = {
  OPEN: 'OPEN',
  INVESTIGATING: 'INVESTIGATING',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  FALSE_POSITIVE: 'FALSE_POSITIVE',
} as const;

const IncidentType = {
  HACK: 'HACK',
  RUG_PULL: 'RUG_PULL',
  FLASH_LOAN_ATTACK: 'FLASH_LOAN_ATTACK',
  EXPLOIT: 'EXPLOIT',
  PHISHING: 'PHISHING',
  FRONT_RUNNING: 'FRONT_RUNNING',
  LIQUIDITY_CRISIS: 'LIQUIDITY_CRISIS',
  GOVERNANCE_ATTACK: 'GOVERNANCE_ATTACK',
} as const;

import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('Missing required environment variable: DATABASE_URL');
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Starting database seeding...');

  // Clear existing data
  await prisma.apiKey.deleteMany();
  await prisma.user.deleteMany();
  await prisma.walletReputationScore.deleteMany();
  await prisma.marketEvent.deleteMany();
  await prisma.contractRiskScore.deleteMany();
  await prisma.incidentFinding.deleteMany();
  await prisma.incidentEntity.deleteMany();
  await prisma.incident.deleteMany();
  await prisma.walletTokenRelation.deleteMany();
  await prisma.tokenMetrics.deleteMany();
  await prisma.token.deleteMany();
  await prisma.contractFinding.deleteMany();
  await prisma.contract.deleteMany();
  await prisma.wallet.deleteMany();

  console.log('🧹 Cleared existing data');

  // Create sample wallets
  const wallets = await Promise.all([
    prisma.wallet.create({
      data: {
        chainId: '1',
        address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b',
        label: 'Whale Wallet #1',
        isBlacklisted: false,
        isWhitelisted: true,
        riskLevel: RiskLevel.LOW,
      },
    }),
    prisma.wallet.create({
      data: {
        chainId: '1',
        address: '0x1111111111111111111111111111111111111111',
        label: 'Suspicious Wallet #1',
        isBlacklisted: true,
        isWhitelisted: false,
        riskLevel: RiskLevel.HIGH,
      },
    }),
    prisma.wallet.create({
      data: {
        chainId: '1',
        address: '0x5aAeb6053f3E94C9b9A09f33669435E7Ef1BeAed',
        label: 'Contract Deployer',
        isContract: false,
        riskLevel: RiskLevel.MEDIUM,
      },
    }),
  ]);

  console.log('💼 Created sample wallets');

  // Create sample contracts
  const contracts = await Promise.all([
    prisma.contract.create({
      data: {
        chainId: '1',
        address: '0xA0b86a33E6441b8e8C7C7b0b8e8e8e8e8e8e8e8e8',
        name: 'USD Coin',
        symbol: 'USDC',
        network: Network.ETHEREUM,
        contractType: ContractType.ERC20,
        deployerAddress: wallets[2].address,
        deploymentBlock: BigInt('12345678'),
        deploymentTx: '0x1234567890abcdef1234567890abcdef12345678',
        isVerified: true,
        totalSupply: '1000000000000000', // 1 trillion USDC
        decimals: 6,
      },
    }),
    prisma.contract.create({
      data: {
        chainId: '1',
        address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8c',
        name: 'Risky DeFi Protocol',
        symbol: 'RISKY',
        network: Network.ETHEREUM,
        contractType: ContractType.DEFI_PROTOCOL,
        deployerAddress: wallets[2].address,
        deploymentBlock: BigInt('12345679'),
        deploymentTx: '0x1234567890abcdef1234567890abcdef12345679',
        isVerified: false,
      },
    }),
    prisma.contract.create({
      data: {
        chainId: '1',
        address: '0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85',
        name: 'ENS: vitalik.eth',
        symbol: 'ENS',
        network: Network.ETHEREUM,
        contractType: ContractType.ERC721,
        deployerAddress: wallets[2].address,
        deploymentBlock: BigInt('12345680'),
        deploymentTx: '0x1234567890abcdef1234567890abcdef12345680',
        isVerified: true,
      },
    }),
  ]);

  console.log('📜 Created sample contracts');

  // NOTE: `IncidentEntity.entityId` is constrained (in the current schema/migration) to both `contracts.id`
  // and `wallets.id`. To keep this seed script working without changing the schema, we create “shadow”
  // rows so the referenced IDs exist in both tables.
  await Promise.all([
    prisma.wallet.create({
      data: {
        id: contracts[1].id,
        chainId: '1',
        address: '0x2222222222222222222222222222222222222222',
        label: 'Shadow Wallet for Contract FK',
        isContract: true,
        riskLevel: RiskLevel.MINIMAL,
      },
    }),
    prisma.contract.create({
      data: {
        id: wallets[2].id,
        chainId: '1',
        address: '0x3333333333333333333333333333333333333333',
        name: 'Shadow Contract for Wallet FK',
        symbol: 'SHADOW',
        network: Network.ETHEREUM,
        contractType: ContractType.CUSTOM,
        isVerified: false,
        isActive: false,
      },
    }),
  ]);

  // Create sample contract findings
  await Promise.all([
    prisma.contractFinding.create({
      data: {
        contractId: contracts[1].id, // Risky DeFi Protocol
        findingType: FindingType.VULNERABILITY,
        severity: Severity.HIGH,
        title: 'Reentrancy Vulnerability',
        description: 'Contract contains a reentrancy vulnerability in the withdraw function.',
        details: {
          function: 'withdraw',
          line: 156,
          recommendation: 'Use checks-effects-interactions pattern',
          cwe: 'CWE-841',
        },
        confidence: 0.95,
        riskScore: 85,
      },
    }),
    prisma.contractFinding.create({
      data: {
        contractId: contracts[1].id,
        findingType: FindingType.SECURITY_BEST_PRACTICE,
        severity: Severity.MEDIUM,
        title: 'Missing Access Control',
        description: 'Critical function lacks proper access control modifiers.',
        details: {
          function: 'setOwner',
          line: 89,
          recommendation: 'Add proper access control modifiers',
        },
        confidence: 0.88,
        riskScore: 65,
      },
    }),
    prisma.contractFinding.create({
      data: {
        contractId: contracts[1].id,
        findingType: FindingType.LIQUIDITY_RISK,
        severity: Severity.CRITICAL,
        title: 'Insufficient Liquidity',
        description: 'Protocol has dangerously low liquidity reserves.',
        details: {
          currentLiquidity: '50000',
          recommendedMinimum: '500000',
          liquidityRatio: 0.1,
        },
        confidence: 0.92,
        riskScore: 92,
      },
    }),
  ]);

  console.log('🔍 Created contract findings');

  // Create sample tokens
  const tokens = await Promise.all([
    prisma.token.create({
      data: {
        address: '0xA0b86a33E6441b8e8C7C7b0b8e8e8e8e8e8e8e8',
        name: 'USD Coin',
        symbol: 'USDC',
        decimals: 6,
        network: Network.ETHEREUM,
        totalSupply: '1000000000000000',
        holderCount: 2500000,
      },
    }),
    prisma.token.create({
      data: {
        address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
        name: 'Dai Stablecoin',
        symbol: 'DAI',
        decimals: 18,
        network: Network.ETHEREUM,
        totalSupply: '5000000000000000000000000',
        holderCount: 1200000,
      },
    }),
    prisma.token.create({
      data: {
        address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
        name: 'Wrapped Ether',
        symbol: 'WETH',
        decimals: 18,
        network: Network.ETHEREUM,
        totalSupply: '3000000000000000000000000',
        holderCount: 800000,
      },
    }),
  ]);

  console.log('🪙 Created sample tokens');

  // Create sample wallet-token relations
  await Promise.all([
    prisma.walletTokenRelation.create({
      data: {
        walletId: wallets[0].id,
        tokenId: tokens[0].id, // USDC
        balance: '1000000000', // 1000 USDC
        usdValue: 1000.0,
        percentage: 25.5,
      },
    }),
    prisma.walletTokenRelation.create({
      data: {
        walletId: wallets[0].id,
        tokenId: tokens[1].id, // DAI
        balance: '500000000000000000000', // 500 DAI
        usdValue: 500.0,
        percentage: 12.75,
      },
    }),
    prisma.walletTokenRelation.create({
      data: {
        walletId: wallets[0].id,
        tokenId: tokens[2].id, // WETH
        balance: '200000000000000000000', // 0.2 WETH
        usdValue: 400.0,
        percentage: 10.2,
      },
    }),
    prisma.walletTokenRelation.create({
      data: {
        walletId: wallets[1].id, // Suspicious wallet
        tokenId: tokens[0].id, // USDC
        balance: '50000000', // 50 USDC
        usdValue: 50.0,
        percentage: 100.0,
      },
    }),
  ]);

  console.log('🔗 Created wallet-token relations');

  // Create sample token metrics
  await Promise.all([
    prisma.tokenMetrics.create({
      data: {
        tokenId: tokens[0].id, // USDC
        contractId: contracts[0].id,
        price: 1.0,
        marketCap: 50000000000,
        volume24h: 2500000000,
        liquidity: 100000000,
        holders: 2500000,
        riskScore: 15,
        volatility24h: 0.5,
        priceChange24h: 0.1,
      },
    }),
    prisma.tokenMetrics.create({
      data: {
        tokenId: tokens[1].id, // DAI
        price: 1.001,
        marketCap: 5000000000,
        volume24h: 150000000,
        liquidity: 50000000,
        holders: 1200000,
        riskScore: 20,
        volatility24h: 1.2,
        priceChange24h: 0.3,
      },
    }),
    prisma.tokenMetrics.create({
      data: {
        tokenId: tokens[2].id, // WETH
        price: 2000.0,
        marketCap: 6000000000,
        volume24h: 300000000,
        liquidity: 75000000,
        holders: 800000,
        riskScore: 35,
        volatility24h: 3.5,
        priceChange24h: -2.1,
      },
    }),
  ]);

  console.log('📊 Created token metrics');

  // Create sample incidents
  const incidents = await Promise.all([
    prisma.incident.create({
      data: {
        title: 'Rug Pull on DeFi Protocol',
        description: 'Protocol developers drained liquidity from the main pool, stealing approximately $2M in user funds.',
        incidentType: IncidentType.RUG_PULL,
        status: IncidentStatus.INVESTIGATING,
        severity: Severity.CRITICAL,
        riskLevel: RiskLevel.CRITICAL,
        network: Network.ETHEREUM,
        amount: '2000000',
        currency: 'USD',
        reportedBy: 'Community Member',
        source: 'Twitter',
        externalUrl: 'https://twitter.com/example/status/123456789',
      },
    }),
    prisma.incident.create({
      data: {
        title: 'Flash Loan Attack on Lending Platform',
        description: 'Attacker exploited a price oracle vulnerability to drain $500K from the platform.',
        incidentType: IncidentType.FLASH_LOAN_ATTACK,
        status: IncidentStatus.OPEN,
        severity: Severity.HIGH,
        riskLevel: RiskLevel.HIGH,
        network: Network.POLYGON,
        amount: '500000',
        currency: 'USD',
        reportedBy: 'Security Researcher',
        source: 'Discord',
        externalUrl: 'https://example.com/incident/123',
      },
    }),
  ]);

  console.log('🚨 Created sample incidents');

  // Create sample incident entities
  await Promise.all([
    prisma.incidentEntity.create({
      data: {
        incidentId: incidents[0].id,
        entityType: 'contract',
        entityId: contracts[1].id, // Risky DeFi Protocol
        role: 'victim',
        details: {
          contractName: 'Risky DeFi Protocol',
          contractAddress: contracts[1].address,
          amountLost: '2000000',
        },
      },
    }),
    prisma.incidentEntity.create({
      data: {
        incidentId: incidents[0].id,
        entityType: 'wallet',
        entityId: wallets[2].id, // Contract Deployer
        role: 'attacker',
        details: {
          walletAddress: wallets[2].address,
          suspicionLevel: 'high',
        },
      },
    }),
    prisma.incidentEntity.create({
      data: {
        incidentId: incidents[1].id,
        entityType: 'contract',
        entityId: contracts[1].id, // Risky DeFi Protocol
        role: 'victim',
        details: {
          contractName: 'Risky DeFi Protocol',
          contractAddress: contracts[1].address,
          amountLost: '500000',
        },
      },
    }),
  ]);

  console.log('👥 Created incident entities');

  // Create sample incident findings
  await Promise.all([
    prisma.incidentFinding.create({
      data: {
        incidentId: incidents[0].id,
        findingType: FindingType.SUSPICIOUS_PATTERN,
        severity: Severity.CRITICAL,
        title: 'Liquidity Drain Pattern',
        description: 'Rapid removal of liquidity from multiple pools within a short timeframe.',
        details: {
          pattern: 'liquidity_drain',
          timeframe: '2 hours',
          poolsAffected: 5,
          totalAmount: '2000000',
        },
        confidence: 0.98,
      },
    }),
    prisma.incidentFinding.create({
      data: {
        incidentId: incidents[1].id,
        findingType: FindingType.VULNERABILITY,
        severity: Severity.HIGH,
        title: 'Price Oracle Manipulation',
        description: 'Attacker manipulated price oracle through flash loan attack.',
        details: {
          vulnerabilityType: 'oracle_manipulation',
          attackVector: 'flash_loan',
          manipulatedAsset: 'ETH/USDC',
        },
        confidence: 0.92,
      },
    }),
  ]);

  console.log('🔬 Created incident findings');

  console.log('✅ Database seeding completed successfully!');
  console.log('\n📈 Summary:');
  console.log(`   - Wallets: ${wallets.length}`);
  console.log(`   - Contracts: ${contracts.length}`);
  console.log(`   - Tokens: ${tokens.length}`);
  console.log(`   - Incidents: ${incidents.length}`);
  console.log(`   - Contract Findings: 3`);
  console.log(`   - Wallet-Token Relations: 4`);
  console.log(`   - Token Metrics: 3`);
  console.log(`   - Incident Entities: 3`);
  console.log(`   - Incident Findings: 2`);
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
    console.log('🔌 Disconnected from database');
  });
